server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://deploypracticeapi-db.cvq0o28uyl1b.ap-northeast-2.rds.amazonaws.com:3306/DeployPracticeAPI?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&connectTimeout=20000&socketTimeout=60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: deployuser
    password: k08095k0223?!
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Swagger ? Api-Docs ??
springdoc:
  swagger-ui:
    enabled: true # swagger ui ???? (?? ???? ??? default? true)
    display-request-duration: true
    persistAuthorization: true # ?? ??? ?? (???? ??? ?????? ?? ??)
    tags-sorter: alpha
    deep-linking: true # API ?? ???? ??? URL ? ?? ?? ?? ( true / false )
  #    supported-submit-methods: # API ???? ??? ?? ?? ( ??? ???? ???? ?? ???? ?? ) ( get / post / patch / put / delete / options / head ? )
  #      - get
  #    try-it-out-enabled: false # ??? ?? ?? ??? ?? ( true / false )
  api-docs:
    groups:
      enabled: true
    enabled: true
  version: 'v1' # API ?? ??
  default-consumes-media-type: application/json # ?? consume media type
  default-produces-media-type: application/json # ?? produce media type
  model-and-view-allowed: true # ModelAndView ??
