server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://deploypracticeapi-db.cvq0o28uyl1b.ap-northeast-2.rds.amazonaws.com:3306/DeployPracticeAPI?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&connectTimeout=10000&socketTimeout=30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: deployuser
    password: k08095k0223?!
    hikari:
        connection-timeout: 30000          # 커넥션 획득 최대 대기 시간 (30초)
        validation-timeout: 5000           # 커넥션 검증 최대 시간 (5초)
        max-lifetime: 1800000              # 커넥션 최대 수명 (30분)
        idle-timeout: 600000               # 커넥션 유휴 최대 시간 (10분)
        minimum-idle: 5                    # 최소 유휴 커넥션 수
        maximum-pool-size: 10              # 최대 커넥션 풀 크기
        connection-test-query: SELECT 1    # 커넥션 검증 쿼리

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

# Swagger ? Api-Docs ??
springdoc:
  swagger-ui:
    enabled: true # swagger ui ???? (?? ???? ??? default? true)
    display-request-duration: true
    persistAuthorization: true # ?? ??? ?? (???? ??? ?????? ?? ??)
    tags-sorter: alpha
    deep-linking: true # API ?? ???? ??? URL ? ?? ?? ?? ( true / false )
  #    supported-submit-methods: # API ???? ??? ?? ?? ( ??? ???? ???? ?? ???? ?? ) ( get / post / patch / put / delete / options / head ? )
  #      - get
  #    try-it-out-enabled: false # ??? ?? ?? ??? ?? ( true / false )
  api-docs:
    groups:
      enabled: true
    enabled: true
  version: 'v1' # API ?? ??
  default-consumes-media-type: application/json # ?? consume media type
  default-produces-media-type: application/json # ?? produce media type
  model-and-view-allowed: true # ModelAndView ??
