server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://deploypracticeapi-db.cvq0o28uyl1b.ap-northeast-2.rds.amazonaws.com:3306/DeployPracticeAPI?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&connectTimeout=20000&socketTimeout=60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: deployuser
    password: k08095k0223?!
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY_ID}
        secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
      s3:
        bucket: deploypractice-static-files
      region:
        static: ap-northeast-2

springdoc:
  swagger-ui:
    enabled: true
    display-request-duration: true
    persistAuthorization: true
    tags-sorter: alpha
    deep-linking: true
  api-docs:
    groups:
      enabled: true
    enabled: true
  version: 'v1'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true
