server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DeployPracticeAPI?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0903

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# Swagger ? Api-Docs ??
springdoc:
  swagger-ui:
    enabled: true # swagger ui ???? (?? ???? ??? default? true)
    display-request-duration: true
    persistAuthorization: true # ?? ??? ?? (???? ??? ?????? ?? ??)
    tags-sorter: alpha
    deep-linking: true # API ?? ???? ??? URL ? ?? ?? ?? ( true / false )
  #    supported-submit-methods: # API ???? ??? ?? ?? ( ??? ???? ???? ?? ???? ?? ) ( get / post / patch / put / delete / options / head ? )
  #      - get
  #    try-it-out-enabled: false # ??? ?? ?? ??? ?? ( true / false )
  api-docs:
    groups:
      enabled: true
    enabled: true
  version: 'v1' # API ?? ??
  default-consumes-media-type: application/json # ?? consume media type
  default-produces-media-type: application/json # ?? produce media type
  model-and-view-allowed: true # ModelAndView ??
